# syntax=docker/dockerfile:1
# Generated by reporewind (renderer 1); do not edit.
# example/calc at c0ffee0000000000000000000000000000000000, recipe sha256:608e23aae2b62d6a323779c395653d63a03124d88ef115d8dc012134bdf8835c
FROM ghcr.io/astral-sh/uv:0.11.29@sha256:eb2843a1e56fd9e30c7276ce1a52cba86e64c7b385f5e3279a0e08e02dd058fc AS uv

FROM python:3.8-slim@sha256:abababababababababababababababababababababababababababababababab
LABEL project=reporewind \
      org.reporewind.repo="example/calc" \
      org.reporewind.commit=c0ffee0000000000000000000000000000000000 \
      org.reporewind.recipe=sha256:608e23aae2b62d6a323779c395653d63a03124d88ef115d8dc012134bdf8835c
ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    PIP_DISABLE_PIP_VERSION_CHECK=1 \
    UV_NO_CACHE=1 \
    UV_PYTHON_DOWNLOADS=never \
    SETUPTOOLS_SCM_PRETEND_VERSION=0.0.0+reporewind
COPY --from=uv /uv /usr/local/bin/uv
RUN useradd --create-home --uid 10001 rewind
COPY requirements.lock /opt/reporewind/requirements.lock
RUN uv pip install --system --exclude-newer 2021-05-11T19:02:03Z --require-hashes -r /opt/reporewind/requirements.lock
WORKDIR /repo
COPY --chown=10001:10001 src/ /repo/
RUN chown -R 10001:10001 /repo
USER 10001:10001
CMD ["python", "-m", "pytest", "-rA"]
